---
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/cmennens/docker/tautulli/config:/config
      - /mnt/plex/movies:/media
    environment:
      - PUID=1000
      - GUID=100
      - TZ=America/Chicago
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
...
