version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: db1
    environment:           # env variables are optional since existing volume is established.
      POSTGRES_DB:         # add your db name.
      POSTGRES_USER:       # add your username.
      POSTGRES_PASSWORD:   # add username password.
    volumes:
      - /home/cmennens/docker/volumes/postgres/db1/data:/var/lib/postgresql/data    # this is a "host" volume (anon|host|named).
      - postgresql_data:/var/lib/postgresql/data   # this is a "named" volume stored in dockers default volume directory.
    networks: 
      - postgresql_network
    ports:
      - "5432:5432"
    restart: unless-stopped

networks:
  postgresql_network:
