version: '3.8'

services:
  debian:
    image: debian:latest
    container_name: debian-1
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - some_network 
    volumes:
      - debian_data_volume:/data

volumes:
  debian_data_volume:
    name: debian_data_volume

networks:
  some_network:
    name: some_network
