---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=latest
      - PLEX_CLAIM="claim-12345"
    volumes:
      - /home/cmennens/docker/plex/config:/config
      - /mnt/data/movies:/movies:ro
      - /dev/dri:/dev/dri 
    tmpfs:
      - /transcode
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:32400/web"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
...
