version: "3.8"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=latest
      - PLEX_CLAIM=""
    volumes:
      - /volume1/docker/plex/config:/config
      - /volume1/plex/movies:/movies
      - /volume1/plex/series:/tv
      - /volume1/plex/music:/music
      - /dev/dri:/dev/dri                     # mount Intel Quic Sync for hardware transoding. Intel CPUs ONLY!!!
    tmpfs:
      - /transcode                            # mount /transcode to in-memory for faster performance
    restart: unless-stopped
