version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo1
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - "27017:27017"
    networks:
      - mongodb_network
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: unless-stopped

  mongo-express:                                   ### View deployent logs for Mongo-Express default credentials. ###
    image: mongo-express:latest
    container_name: mongo-ex1
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo1
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=            ### add your MongoDB user credentials w/ userAdminAnyDatabase or userAdmin roles ###
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
    networks:
      - mongodb_network
    restart: unless-stopped

networks:
  mongodb_network:
    name: mongodb_network

volumes:
  mongodb_data:
    name: mongodb_data_volume
  mongodb_config:
    name: mongodb_config_volume
