version: '3.8'

services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_REPLICA_SET_NAME: rs0
    ports:
      - "27017:27017"
    volumes:
      - mongo1_config:/data/configdb
      - mongo1_data:/data/db
    networks:
      - mongo_network

  mongo2:
    image: mongo:latest
    container_name: mongo2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_REPLICA_SET_NAME: rs0
    ports:
      - "27018:27017"
    volumes:
      - mongo2_config:/data/configdb
      - mongo2_data:/data/db
    networks:
      - mongo_network

  mongo3:
    image: mongo:latest
    container_name: mongo3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_REPLICA_SET_NAME: rs0
    ports:
      - "27019:27017"
    volumes:
      - mongo3_config:/data/configdb
      - mongo3_data:/data/db
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongo1_config:
  mongo1_data:
  mongo2_config:
  mongo2_data:
  mongo3_config:
  mongo3_data:
