---
services:
  postgres:
    container_name: semaphore_db
    hostname: semaphore_db
    restart: unless-stopped
    networks:
      - semaphore_network
    ports:
      - 5432:5432
    image: postgres:latest
    volumes:
      - semaphore_db_config:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: semaphore
      POSTGRES_PASSWORD: {{ pg_pw }}
      POSTGRES_DB: semaphore_db

  semaphore:
    container_name: semaphore_ui
    hostname: semaphore_ui
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - semaphore_network
    ports:
      - 3000:3000
    volumes:
      - semaphore_config:/etc/semaphore
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: {{ pg_pw }}
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: semaphore_db
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: {{ ui_pw }}
      SEMAPHORE_ADMIN_NAME: Semaphore UI Admin
      SEMAPHORE_ADMIN_EMAIL: semaphore@hubgroup.com
      SEMAPHORE_ADMIN: semaphore
      SEMAPHORE_ACCESS_KEY_ENCRYPTION:
      SEMAPHORE_LDAP_ACTIVATED: 'no'
      ANSIBLE_HOST_KEY_CHECKING: 'false'
    depends_on:
      - postgres

networks:
  semaphore_network:
    driver: bridge

volumes:
  semaphore_db_config:
  semaphore_config:
...
