services:
  postgres:
    container_name: semaphore_db
    hostname: semaphore_db
    restart: unless-stopped
    networks:
      - semaphore_network
    ports:
      - 5432:5432
    image: postgres:latest
    volumes: 
      - postgres_data_vol:/var/lib/postgresql/data
      - postgres_logs_vol:/var/lib/postgresql/logs
      - /path/to/requirements.txt:/etc/semaphore/requirements.txt   # Change the source to your local path.
    environment:
     POSTGRES_USER: secet.PG_USER
     POSTGRES_PASSWORD: secret.PG_PW
     POSTGRES_DB: semaphore_db
  
  semaphore:
    container_name: semaphore_ui
    hostname: semaphore_ui
    restart: unless-stopped
    networks:
      - semaphore_network
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    volumes: 
      - semaphore_vol:/data
    environment:
      SEMAPHORE_DB_USER: 
      SEMAPHORE_DB_PASS: 
      SEMAPHORE_DB_HOST: 
      SEMAPHORE_DB_PORT: 
      SEMAPHORE_DB_DIALECT: postgres 
      SEMAPHORE_DB: 
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: 
      SEMAPHORE_ADMIN_NAME: 
      SEMAPHORE_ADMIN_EMAIL: 
      SEMAPHORE_ADMIN: 
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: 
      SEMAPHORE_LDAP_ACTIVATED: 'no'
      ANSIBLE_HOST_KEY_CHECKING: 'false'
    depends_on:
      - postgres 

networks:
  ansible_network:
    driver: bridge

volumes:
  postgres_data_vol:
  postgres_logs_vol:
  semaphore_vol:
