version: '3.8'
services:
  postgres:
    container_name: 
    restart: unless-stopped
    networks:
      - ansible_network
    ports:
      - 5432:5432
    image: postgres:latest
    volumes: 
      - postgres_volume:/var/lib/postgresql/data
    environment:
     POSTGRES_USER: 
     POSTGRES_PASSWORD: 
     POSTGRES_DB: 
  
  semaphore:
    container_name: 
    restart: unless-stopped
    networks:
      - ansible_network
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    volumes: 
      - ansible_volume:/data
    environment:
      SEMAPHORE_DB_USER: 
      SEMAPHORE_DB_PASS: 
      SEMAPHORE_DB_HOST: 
      SEMAPHORE_DB_PORT: 
      SEMAPHORE_DB_DIALECT: postgres 
      SEMAPHORE_DB: 
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: 
      SEMAPHORE_ADMIN_NAME: 
      SEMAPHORE_ADMIN_EMAIL: 
      SEMAPHORE_ADMIN: 
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: 
      SEMAPHORE_LDAP_ACTIVATED: 'no'
      ANSIBLE_HOST_KEY_CHECKING: 'false'
    depends_on:
      - postgres 

networks:
  ansible_network:
    driver: bridge

volumes:
  postgres_volume:
  ansible_volume:
