version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest    # will use the latest tag.
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  portainer_data:    # creates a volume in the default docker volume directory which mounts to /data on the container.
