version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: pg1
    restart: always
    environment:
      POSTGRES_DB:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    ports:
      - "5532:5432"       # host:container
    volumes:
      - pg1_data:/var/lib/postgresql/data

volumes:
  pg1_data:                # volumes are stored in /var/lib/docker/volumes on the host

