version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: pg1
    restart: always
    environment:
      POSTGRES_DB:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    volumes:
      - pg1_data:/var/lib/postgresql/data

volumes:
  pg1_data:

